### ISSUE TITLE
Searching for tags?

### ISSUE THREAD

**Issue by DarthMarauder** [ColdTrick/search_advanced#15]
When I serach for tags, they aren't "separated" anymore.
For example, in normal Elgg when I click on a tag (for example in a page), elgg sends me to
mysite.com/search?q=tagword+11&search_type=tags
where I get only results with content that is tagged with 'tagword 11'

With search_advanced, when I click on 'tagword 11', elgg sends me to the same address
mysite.com/search?q=tagword+11&search_type=tags 
But I get all kinds of other results in addition to the results that have 'tagword 11'. 
Also it seems strange that tags aren't listed in the search box's dropdown menu.

Searching Discussion Topics is a pain. I don't get any results from the Topic title or content. The only way to get a result is if the topic is taged and I search by the tagword. The same with bookmarks. If I try to find a bookmark tagged 'blue green' and only search with the word blue, I don't get any results. I have to write exactly 'blue green'.

Is there something I'm missing?

**Comment by jdalsem** [comment]
Tags are no longer separate with this plugin, but combined with the entities they belong to.
