### ISSUE TITLE
Non English Language search words don't work

### ISSUE THREAD

**Issue by merilturock** [ColdTrick/search_advanced#16]
In the search i used a Tamil word to search but the search returns a blank white page. Kindly make the search available for all languages.

**Comment by merilturock** [comment]
Also if i select a particular entity say blog my search returns a empty page..

http://connectgalaxy.com/search?search_type=entities&entity_type=object&entity_subtype=blog&q=bible

**Comment by jdalsem** [comment]
Did you try this with the search_advanced plugin disabled?

**Comment by merilturock** [comment]
Yes i tried it works perfectly without any problem but when enabling advance search i get a white screen.

**Comment by jdalsem** [comment]
Can you take a look into you php error log and see if there is any error being reported? You could also turn on display_errors in your htaccess file to view the errors on site (instead of the white page).
