### ISSUE TITLE
delayed loading option causes JS document 'ready' event to not be called

### ISSUE THREAD

**Issue by propertunist** [ColdTrick/search_advanced#18]
i have some jquery code which runs on most pages during the document's 'ready' event and when i enable the 'use delayed search' option, this code does not get triggered.
the rest of the code runs as expected and the HTML that is being effected is within the elgg sidebar as a widget. i did not know there was a way for the document ready function to be prevented from being triggered so easily, so i imagine the problem is that the document ready event is being triggered once the search result is loaded and the context of the event is a different document to the main container document in elgg.

**Comment by jdalsem** [comment]
This commit probably fixes it https://github.com/ColdTrick/search_advanced/commit/0e8c540a005b4dc2789729631662c884bc4fb207
