### ISSUE TITLE
Supported Features

### ISSUE THREAD

**Issue by solace** [ColdTrick/search_advanced#21]
Hi,

This repository suggests that there is a Elgg 1.8 supported branch (https://github.com/ColdTrick/search_advanced/tree/elgg_18), but the plugin page on Elgg doesn't have this listed: https://elgg.org/plugins/2261455

Can you please confirm if Elgg 1.8 is supported?

Also, does this search plugin support limiting searches to certain types? For example, searching for a term within a specific group, or searching for a tag within a specific group.  If not, as you have worked with this aspect of core, are you aware of whether this functionality is supported with the existing hooks and handlers that are available?  The documentation on this feature and supported parameters is somewhat lean.

Thanks

**Comment by jdalsem** [comment]
The 1.8 tree is indeed the tree for a working version of SearchAdvanced for Elgg 1.8, however Elgg 1.8 is very outdated and i am not suggesting you should use that.

The specific features you describe can be achievable with some additional programming, but are no current feature of core or this plugin. The documentation is indeed very thin on this subject. The search features are not the best part of Elgg. Integrations with SOLR (https://github.com/arckinteractive/elgg_solr) or Elastic (https://github.com/ColdTrick/elasticsearch) should provide you with much better search options, but those plugins require newer version of Elgg.
