### ISSUE TITLE
Users can be found on private metadata

### ISSUE THREAD

**Issue by oseg** [ColdTrick/search_advanced#29]
Context:
- elgg v1.12.8 (clean install with default settings)
- search advanced v2.0: only external plugin installed and activated

Scenario:
- log in as admin
- Create a new user "test_user"
- Edit "test_user" profile
- Enter "Armageddon" (for instance) in interest field (tag field) and set accessibility as private
- Enter "Babylone" (for instance) in telephone field (text field) and set accessibility as private
- Save user profile
- log out, go to members page, click on "test_user" profile page
  => "Armageddon" and "Babylone" are not displayed, only public content is displayed
- Go back to the "members" page and enter "Armageddon" or "Babylone" in the search box
  => "test user" is displayed in the search results
  => "Armageddon" and "Babylone" are NOT displayed in the search results (of course, their are private)

"test_user" should not be found by the search
Deactivate "Search advanced" plugin and replay the same scenario
=> "test user" is NOT displayed in the search results

Workaround in the plugin settings:
Check "Do not use in metadata search" for all user profile fields or set 'Search Advanced should control the search results' to 'No'
But this workaround is not very satisfying because it disables user profile metadata search...

**Comment by oseg** [comment]
Issue also reproduced in v2.1.1

I found the root cause: the metadata access level is not checked in the user search request
Potential fix in "search_advanced_users_hook" function: 

In hooks.php file, at line 476, replace
```
$md_where = "((md$i.name_id IN (" . implode(",", $tag_name_ids) . ")) AND (" . implode(" OR ", $likes) . "))";
```
by
```
$access = _elgg_get_access_where_sql(array('table_alias' => "md$i")); // Add access controls
$md_where = "(((md$i.name_id IN (" . implode(",", $tag_name_ids) . ")) AND (" . implode(" OR ", $likes) . ")) AND $access)";
```
And at line 506, replace
```
// do a soundex match
if (is_array($profile_soundex) && in_array($field_name, $profile_soundex)) {
	$profile_field_likes[] = "md$i.name_id = $tag_name_id AND soundex(CONCAT('X', msv$i.string)) = soundex(CONCAT('X','$field_value'))";
} else {
	$profile_field_likes[] = "md$i.name_id = $tag_name_id AND msv$i.string LIKE '%$field_value%'";
}
```
by
```
$access = _elgg_get_access_where_sql(array('table_alias' => "md$i")); // Add access controls
// do a soundex match
if (is_array($profile_soundex) && in_array($field_name, $profile_soundex)) {
	$profile_field_likes[] = "(md$i.name_id = $tag_name_id AND soundex(CONCAT('X', msv$i.string)) = soundex(CONCAT('X','$field_value'))) AND $access";
} else {
	$profile_field_likes[] = "(md$i.name_id = $tag_name_id AND msv$i.string LIKE '%$field_value%') AND $access";
}
```
There is probably a similar issue in search_advanced_groups_hook()

**Comment by oseg** [comment]
The issue is not reproduced with group profiles, because group profiles don't have an UI to choose the access level of their metadata: profile manager group fields.

**Comment by jdalsem** [comment]
In Elgg 3 and the Elgg 3 version of this plugin this is no longer an issue in this plugin
