### ISSUE TITLE
"answer", "page_top" and "discussion_reply" subtypes not managed correctly in "combine objects" and "combine all" search results

### ISSUE THREAD

**Issue by oseg** [ColdTrick/search_advanced#30]
**Context:**
- elgg v1.12.11
- search_advanced v2.1.1 with the following settings:
  . combine search results: combine objects
- questions v2.0.1

**Scenario:**
Notice: The "Answer" entity is not in the search filter menu while "Question" is in.
1- Let's keep "All" in the filter menu, and launch a search on the key word "test"
2- An "Answer" containing the key word "test" is displayed among the other search results, however the "Refine the results" menu does not propose "Answer" in its list
3- Anyway, let's click on the "Answers" hyperlink, displayed at the end of the answer result line
4- a new page is displayed with "0 results for test", and now "Answers(0)" is displayed in the "Refine the results" menu
5- To get the answer and question results, I have to click on the "Questions(2)" item in the "Refine the results" menu

"Answers" results seem to be displayed in "Questions" results... then the "Answers" hyperlink, displayed at the end of the answer result line should be a "Questions" hyperlink.

**Comment by oseg** [comment]
Suggested fix: add following line in views/default/search_advanced/search/floating_tag.php at line 18:

```
if (elgg_is_active_plugin('questions') && ($subtype === 'answer')) {
    $subtype = "question";
}

```

**Comment by oseg** [comment]
Same bug with top-level pages, same kind of fix:
```
if (elgg_is_active_plugin('pages') && ($subtype === 'page_top')) {
    $subtype = "page";
}

```

**Comment by oseg** [comment]
Same bug with discussion reply, same kind of fix:
```
if (elgg_is_active_plugin('groups') && ($subtype === 'discussion_reply')) {
    $subtype = 'groupforumtopic';
}
```

**Comment by jdalsem** [comment]
In Elgg 3 this is no longer and issue
