### ISSUE TITLE
Design issues on iPhone 6S

### ISSUE THREAD

**Issue by javery86** [ColdTrick/search_advanced#34]
The search box is cut off and the drop down of search categtoies is cut off on the left side. Also, the category “All” should be forced to the top and not in alphabetical order.

**Comment by jdalsem** [comment]
> Also, the category “All” should be forced to the top and not in alphabetical order.

See https://github.com/ColdTrick/search_advanced/issues/33



> The search box is cut off and the drop down of search categtoies is cut off on the left side.

Only on iPhone 6s? Or on all smaller screen sizes?

**Comment by javery86** [comment]
I only checked on an iPhone 6S.

**Comment by jdalsem** [comment]
Unable to reproduce with latest version. Please provide screenshot if you still experience the problem
