### ISSUE TITLE
Type selection is not working

### ISSUE THREAD

**Issue by Max9316** [ColdTrick/search_advanced#38]
**Elgg version**
3.3.12

**Plugin version**
6.0

**Plugin source**
- Github releases download

**Describe the bug**
Type selection is not working.

**To Reproduce**
1. Go to the search bar on index page for example and type in 'test'
2. Select the type 'group' via drop down menu in the search bar
3. Enter your search

**Expected behavior**
I would expect a search result which is filtered by the type 'group' like when i click the menu item 'group' in the sidebar of the search page. Instead I receive an unfiltered result of all types.

**Screenshots**
Currently:
![image](https://user-images.githubusercontent.com/42812986/110460287-4427a800-80ce-11eb-892f-2f97fe003cfd.png)
Expected via group menu item:
![image](https://user-images.githubusercontent.com/42812986/110460391-691c1b00-80ce-11eb-9b66-12062fdb7724.png)

**Additional context**
Maybe I am missing something here, if so I would be very happy if you could enlighten me.

Best regards,
Max

**Comment by jdalsem** [comment]
Should be working as you described (AFAIK). Will investigate

**Comment by Max9316** [comment]
Ok, thanks for the quick response! :)
